#!/usr/bin/env python
# get all [txt, md, markdown, use-configuration] files in [give or current] dir and all its subdirs
# store file names, relative paths, text contents
# create UIs to list and preview:
#     current files
#     archived files
#     removed files

# subdirs are ignored when archiving/trashing

# .lil/
# .lil/archived
# .lil/removed

import re
import os
import sys
import getopt
import curses

sys.path = sys.path[1:]


VALID_OPTIONS_SHORT = "rg"
VALID_OPTIONS_LONG = ""

def main(argv=None):
  opt_recursive = False
  opt_gui_enabled = False
  if argv is None:
    argv = sys.argv

  if len(argv) > 1:
    opts, args = getopt.getopt(argv[1:], VALID_OPTIONS_SHORT, VALID_OPTIONS_LONG)

    if len(args) > 0:
      notes_root = args[0]
    else:
      notes_root = '.'

    for opt, arg in opts:
      if opt in ('-r'):
        opt_recursive = True
      elif opt in ('-g'):
        opt_gui_enabled = True

  else:
    notes_root = os.curdir

  import tix.utils
  root_dir = os.path.join(tix.utils.HOME_DIR, 'tix')
  if opt_gui_enabled:
    import tix.gtk_main
    gtk_app = tix.gtk_main.GtkMain()
    gtk_app.main(notes_root, opt_recursive)
  else:
    import tix.curses_main
    curses.wrapper(tix.curses_main.CursesMain.main, notes_root, opt_recursive)

if __name__ == "__main__":
  sys.exit(main())
